import type { FieldArrayPath, Path } from "react-hook-form";
import type { NuvoletsContent } from "@/lib/schemas/nuvolets";

export type NuvoletsField = { name: Path<NuvoletsContent>; label: string; type?: "textarea" | "image" | "boolean" | "tone" | "color" };
export type NuvoletsList = { name: FieldArrayPath<NuvoletsContent>; label: string; fields: { name: string; label: string; type?: NuvoletsField["type"] }[] };
export const NUVOLETS_EDITOR_COPY = { add: "Añadir", remove: "Eliminar", up: "Subir", down: "Bajar", validate: "Validar cambios", applied: "Cambios aplicados. Usa Guardar o Publicar para conservarlos.", invalid: "Revisa los campos de la plantilla", addProduct: "Añadir producto", productsTitle: "Productos", productsDescription: "Añade productos al catálogo informativo. La configuración avanzada llegará más adelante.", name: "Nombre", price: "Precio visible (opcional)", image: "Imagen", alt: "Texto alternativo", added: "Producto añadido. Guarda o publica los cambios.", maximum: "El catálogo admite hasta 200 productos", empty: "Todavía no hay productos", preview: "La newsletter está desactivada en la vista previa", privacy: "Política de privacidad" };
export const NUVOLETS_TONES = [{ value: "blue", label: "Azul" }, { value: "pink", label: "Rosa" }, { value: "yellow", label: "Amarillo" }, { value: "sage", label: "Salvia" }];

const imageFields = [{ name: "image", label: "Imagen", type: "image" }, { name: "alt", label: "Texto alternativo" }] as const;
const textFields = [{ name: "title", label: "Título" }, { name: "text", label: "Texto", type: "textarea" }] as const;
const links = [{ name: "label", label: "Texto" }, { name: "href", label: "Enlace" }];
const messages = [{ name: "text", label: "Mensaje" }];
const fields = (prefix: string, items: readonly { name: string; label: string; type?: NuvoletsField["type"] }[]): NuvoletsField[] => items.map((item) => ({ ...item, name: `${prefix}.${item.name}` as Path<NuvoletsContent> }));

export const NUVOLETS_EDITOR_FIELDS: Record<string, { fields: NuvoletsField[]; lists: NuvoletsList[] }> = {
  Hero: { fields: fields("heroDetails", [{ name: "alt", label: "Texto alternativo del hero" }, { name: "primaryHref", label: "Enlace principal" }, { name: "secondaryLabel", label: "Botón secundario" }, { name: "secondaryHref", label: "Enlace secundario" }]), lists: [] },
  Franja: { fields: [], lists: [{ name: "marquee", label: "Mensajes de la franja", fields: messages }] },
  Categorías: { fields: [], lists: [{ name: "categories", label: "Categorías", fields: [{ name: "title", label: "Nombre" }, { name: "description", label: "Descripción", type: "textarea" }, ...imageFields, { name: "href", label: "Enlace" }, { name: "tone", label: "Color", type: "tone" }] }] },
  Colección: { fields: fields("collection", [{ name: "title", label: "Título" }, { name: "subtitle", label: "Descripción", type: "textarea" }, { name: "note", label: "Texto de contacto", type: "textarea" }, { name: "linkLabel", label: "Texto del enlace" }, { name: "href", label: "Enlace" }]), lists: [] },
  Historia: { fields: fields("story", [...textFields, { name: "secondaryText", label: "Texto secundario", type: "textarea" }, ...imageFields, { name: "ctaLabel", label: "Botón" }, { name: "ctaHref", label: "Enlace del botón" }]), lists: [] },
  Favoritos: { fields: fields("favorites", [{ name: "title", label: "Título" }, { name: "subtitle", label: "Descripción", type: "textarea" }]), lists: [] },
  Tienda: { fields: fields("store", [{ name: "eyebrow", label: "Etiqueta" }, ...textFields, ...imageFields, { name: "ctaLabel", label: "Botón" }, { name: "mapsUrl", label: "Enlace al mapa" }, { name: "secondaryLabel", label: "Enlace secundario" }, { name: "secondaryHref", label: "Destino secundario" }]), lists: [] },
  Instagram: { fields: fields("instagram", [...textFields, { name: "buttonLabel", label: "Botón" }, { name: "url", label: "Perfil de Instagram" }]), lists: [{ name: "instagram.images", label: "Galería", fields: [...imageFields, { name: "href", label: "Enlace de la imagen" }, { name: "tone", label: "Color", type: "tone" }] }] },
  Newsletter: { fields: fields("newsletter", [{ name: "enabled", label: "Activar captación de emails", type: "boolean" }, ...textFields, { name: "placeholder", label: "Texto del campo email" }, { name: "buttonLabel", label: "Botón" }, { name: "consentText", label: "Aviso de consentimiento", type: "textarea" }, { name: "privacyUrl", label: "Enlace de privacidad" }]), lists: [] },
  Mascota: { fields: fields("mascot", [{ name: "enabled", label: "Mostrar mascota", type: "boolean" }, { name: "name", label: "Nombre" }, ...imageFields]), lists: [{ name: "mascot.messages", label: "Mensajes", fields: messages }] },
  Diseño: { fields: [...fields("effects", [{ name: "decorations", label: "Mostrar decoraciones", type: "boolean" }, { name: "motion", label: "Activar animaciones", type: "boolean" }]), ...fields("colors", [{ name: "enabled", label: "Usar colores personalizados", type: "boolean" }, ...["background", "surface", "text", "border", "blue", "pink", "yellow", "sage"].map((name, i) => ({ name, label: ["Fondo", "Superficie", "Texto", "Bordes", "Azul", "Rosa", "Amarillo", "Salvia"][i], type: "color" as const }))])], lists: [] },
  Footer: { fields: fields("footer", [{ name: "description", label: "Descripción", type: "textarea" }, { name: "exploreTitle", label: "Título de navegación" }, { name: "infoTitle", label: "Título de información" }, { name: "socialTitle", label: "Título de redes" }, { name: "copyright", label: "Pie legal", type: "textarea" }]), lists: [{ name: "footer.exploreLinks", label: "Enlaces de navegación", fields: links }, { name: "footer.infoLinks", label: "Enlaces de información", fields: links }, { name: "footer.socialLinks", label: "Redes", fields: links }] },
};
