export const PRODUCT_DRAWER_COPY = {
  newTitle: "Nuevo producto",
  editTitle: "Editar producto",
  newDescription: "Añade contenido, imágenes y variantes",
  editDescription: "Edita contenido, imágenes y variantes",
  cancel: "Cancelar",
  save: "Guardar",
  saving: "Guardando…",
  state: "Estado",
  preview: "Vista previa",
  close: "Cerrar",
  navGroup: "Producto",
  navLabel: "Secciones del producto",
  navInformation: "Información",
  navImages: "Imágenes",
  navVariants: "Variantes",
  navCharacteristics: "Características",
  navSeo: "SEO",
  navInvalid: "Con errores",
  sectionGeneral: "Información general",
  sectionGeneralDescription: "La información principal que verá el cliente.",
  sectionImages: "Imágenes",
  sectionImagesDescription: "La primera imagen será la portada del producto.",
  sectionVariants: "Variantes e inventario",
  sectionVariantsDescription: "Tallas, colores, SKU, stock y precios.",
  sectionCharacteristics: "Características",
  sectionCharacteristicsDescription: "Información adicional del producto.",
  sectionSeo: "SEO",
  sectionSeoDescription: "Cómo aparecerá el producto en buscadores.",
  addVariant: "Añadir variante",
  dirty: "Cambios sin guardar",
  clean: "Sin cambios pendientes",
} as const;
