export const PRODUCTS_LIST_COPY = {
  configure: "Configurar catálogo",
  new: "Nuevo producto",
  search: "Buscar por nombre, SKU o categoría",
  searchLabel: "Buscar productos",
  filters: "Filtros",
  filtersTitle: "Filtrar catálogo",
  sort: "Ordenar",
  sortLabel: "Orden del catálogo",
  productsCount: "productos",
  clearFilters: "Limpiar",
  activeFilters: "Filtros:",
  tabs: {
    all: "Todos",
    published: "Publicados",
    draft: "Borradores",
    archived: "Archivados",
  },
  columns: {
    product: "Producto",
    status: "Estado",
    inventory: "Inventario",
    category: "Categoría",
    price: "Precio",
    actions: "Acciones del producto",
  },
  status: {
    published: "Publicado",
    draft: "Borrador",
    archived: "Archivado",
  },
  stock: {
    pending: "Stock pendiente",
    out: "Sin stock",
    low: "Stock bajo",
    ok: "Disponible",
  },
  sortOptions: {
    newest: "Novedades",
    priceAsc: "Precio: menor a mayor",
    priceDesc: "Precio: mayor a menor",
  },
  availability: {
    all: "Toda disponibilidad",
    available: "Disponible",
    out: "Agotado",
    pending: "Stock pendiente",
  },
  filterLabels: {
    category: "Categoría",
    brand: "Marca",
    size: "Talla",
    availability: "Disponibilidad",
    search: "Búsqueda",
  },
  batch: {
    selectedOne: "1 seleccionado",
    selectedMany: (count: number) => `${count} seleccionados`,
    publish: "Publicar",
    archive: "Archivar",
    clear: "Cancelar selección",
  },
  row: {
    edit: "Editar",
    duplicate: "Duplicar",
    publish: "Publicar",
    unpublish: "Retirar",
    archive: "Archivar",
    restore: "Restaurar",
  },
  pagination: {
    label: "Paginación del catálogo",
    showing: (from: number, to: number, total: number) => `Mostrando ${from}–${to} de ${total} productos`,
    previous: "Página anterior",
    next: "Página siguiente",
  },
  applyFilters: "Aplicar",
  allCategories: "Todas las categorías",
  allBrands: "Todas las marcas",
  allSizes: "Todas las tallas",
} as const;
