export const PRODUCT_DRAWER_COPY = {
  newTitle: "Nuevo producto",
  editTitle: "Editar producto",
  newDescription: "Añade la información, imágenes y variantes del producto.",
  editDescription: "Actualiza la información, imágenes y variantes del producto.",
  cancel: "Cancelar",
  save: "Guardar",
  saving: "Guardando…",
  state: "Estado",
  preview: "Vista previa",
  close: "Cerrar",
  sectionGeneral: "Información general",
  sectionData: "Datos del producto",
  sectionImages: "Imágenes",
  sectionVariants: "Variantes y existencias",
  sectionCharacteristics: "Otras características",
  addImage: "Añadir imagen",
  addVariant: "Añadir variante",
  addCharacteristic: "Añadir característica",
} as const;
