export const PRODUCT_CATEGORIES_COPY = {
  title: "Categorías",
  description: "Crea categorías para organizar tus productos. Al renombrarlas, se actualizan todos los productos que las utilizan.",
  empty: "Todavía no hay categorías. Crea la primera para empezar a organizar tus productos.",
  new: "Nueva categoría",
  edit: "Editar categoría",
  editLabel: (name: string) => `Editar categoría ${name}`,
  name: "Nombre de la categoría",
  placeholder: "Por ejemplo, Conjuntos",
  create: "Crear categoría",
  save: "Guardar cambios",
  saving: "Guardando…",
  cancel: "Cancelar edición",
  created: "Categoría creada",
  updated: "Categoría actualizada",
  invalid: "Revisa el nombre de la categoría",
  error: "No se pudo guardar la categoría",
} as const;
