import type { TemplateDefinition } from "@/lib/templates/types";
import { NAV_EDITOR_TAB, DESIGN_EDITOR_TAB, OFFERS_EDITOR_TAB, RESERVAS_EDITOR_TAB, BLOG_EDITOR_TAB, FOOTER_EDITOR_TAB, SEO_EDITOR_TAB, SECTIONS_EDITOR_TAB } from "@/lib/templates/editor-tabs";

export const PORTFOLIO_TEMPLATE: TemplateDefinition = {
  id: "portfolio",
  label: "Portfolio",
  description: "Landing para profesionales creativos: proyectos, servicios, testimonios y contacto.",
  retired: false,
  contentVersion: 1,
  rendererVersion: 1,
  storageSections: [
  "hero",
  "branding",
  "story",
  "gallery",
  "nav",
  "testimonials",
  "cta",
  "serviceMenu",
  "benefits",
  "workHistory",
  "faq",
],
  capabilities: { newsletter: false, booking: true },
  sections: [
  { anchor: "hero", label: "Hero", editorTabId: "Hero", required: true },
  { anchor: "story", label: "Historia", navHref: "#story", contentKeys: ["story"] },
  { anchor: "experiencia", label: "Experiencia", editorTabId: "Experiencia", navHref: "#experiencia", contentKeys: ["workHistory"] },
  { anchor: "proyectos", label: "Proyectos", editorTabId: "Proyectos", navHref: "#proyectos", contentKeys: ["gallery"] },
  { anchor: "testimonios", label: "Testimonios", navHref: "#testimonios", contentKeys: ["testimonials"] },
  { anchor: "servicios", label: "Servicios", editorTabId: "Servicios", navHref: "#servicios", contentKeys: ["serviceMenu"] },
  { anchor: "skills", label: "Cómo trabajo", editorTabId: "Cómo trabajo", navHref: "#skills", contentKeys: ["benefits"] },
  { anchor: "faq", label: "FAQ", editorTabId: "FAQ", navHref: "#faq", contentKeys: ["faq"] },
  { anchor: "reservas", label: "Reservas", editorTabId: "Reservas", navHref: "#reservas" },
  { anchor: "contacto", label: "Pie de página", editorTabId: "Footer", navHref: "#contacto", required: true },
],
  headings: {
    experiencia: {
      title: "Experiencia laboral",
      subtitle: "",
    },
    proyectos: {
      title: "Proyectos seleccionados",
      subtitle: "",
    },
    skills: {
      title: "Cómo trabajo",
      subtitle: "",
    },
    servicios: {
      title: "Servicios",
      subtitle: "",
    },
    faq: {
      title: "Preguntas frecuentes",
      subtitle: "Todo lo que necesitas saber antes de empezar un proyecto juntos.",
    },
    contacto: {
      title: "Hablemos de tu proyecto",
      subtitle: "Cuéntame tu idea y diseñemos juntos algo memorable.",
    },
    reservas: {
      title: "Reserva una consulta",
      subtitle: "Elige servicio, profesional y horario.",
    },
  },
  paletteOptions: [
    { id: "default", label: "Original", description: "Negro tinta y turquesa.", colorScheme: "dark" },
    { id: "lime", label: "Lima", description: "Carbón y verde eléctrico.", colorScheme: "dark" },
    { id: "coral", label: "Coral", description: "Grafito y coral vivo.", colorScheme: "dark" },
    { id: "ivory", label: "Marfil", description: "Marfil cálido y azul cobalto.", colorScheme: "light" },
    { id: "sand", label: "Arena", description: "Arena suave y terracota.", colorScheme: "light" },
    { id: "mist", label: "Niebla", description: "Gris niebla y violeta.", colorScheme: "light" },
    { id: "sky", label: "Cielo", description: "Azul cielo y océano.", colorScheme: "light" },
    { id: "blush", label: "Rubor", description: "Rosa claro y borgoña.", colorScheme: "light" },
  ],
  editorTabs: [
      { id: "Hero", label: "Hero" },
      NAV_EDITOR_TAB,
      DESIGN_EDITOR_TAB,
      { id: "Experiencia", label: "Experiencia" },
      { id: "Proyectos", label: "Proyectos" },
      { id: "Cómo trabajo", label: "Cómo trabajo" },
      { id: "Servicios", label: "Servicios" },
      { id: "FAQ", label: "FAQ" },
      OFFERS_EDITOR_TAB,
      RESERVAS_EDITOR_TAB,
      BLOG_EDITOR_TAB,
      FOOTER_EDITOR_TAB,
      SEO_EDITOR_TAB,
      SECTIONS_EDITOR_TAB,
    ],
  loadImageOptions: () => import("@/lib/templates/portfolio/image-options").then((module) => module.PORTFOLIO_IMAGE_OPTIONS),
  loadContent: () => import("@/lib/templates/portfolio/content").then((module) => module.PORTFOLIO_DEFAULT_CONTENT),
  loadComponent: () => import("@/components/templates/portfolio/portfolio-template").then((module) => module.PortfolioTemplate),
  loadEditor: () => import("@/components/dashboard/sections/portfolio-editor-section").then((module) => module.PortfolioEditorSection),
};
