export const SUBSCRIPTION_SETTINGS_COPY = {
  subscribersTab: "Suscriptores",
  settingsTab: "Configuración",
  enabled: "Activar suscripciones",
  enabledHelp: "Muestra el formulario en tu web y permite registrar emails. Requiere completar los datos del responsable.",
  controllerTitle: "Responsable del tratamiento",
  controllerName: "Nombre o razón social",
  controllerAddress: "Dirección",
  contactEmail: "Email de contacto",
  contactEmailHelp: "Se muestra en la política de privacidad para ejercer derechos y solicitar la baja.",
  consentTitle: "Aviso de consentimiento",
  consentText: "Texto junto a la casilla",
  consentHelp: "El visitante debe marcar la casilla con este texto antes de suscribirse. Se añade un enlace a la política de privacidad.",
  privacyTitleSection: "Política de privacidad",
  privacyTitle: "Título de la página",
  privacyText: "Texto de la política",
  privacyHelp: "Escribe ## al inicio de una línea para crear un apartado. Puedes usar {{responsable}}, {{direccion}} y {{email}}: se sustituyen por tus datos.",
  restore: "Restaurar textos por defecto",
  preview: "Ver política de privacidad",
  previewHelp: "La política se publica automáticamente en la dirección /suscripciones/privacidad de tu web cuando las suscripciones están configuradas.",
  save: "Guardar configuración",
  saving: "Guardando…",
  saved: "Configuración guardada",
  invalid: "Revisa los datos de las suscripciones",
  failed: "No se pudo guardar la configuración. Inténtalo más tarde.",
} as const;
